name: Lint
on:
    push: { branches: [main] }
    pull_request:
permissions:
    contents: read

jobs:
    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with: { persist-credentials: false }
            - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
              with: { components: rustfmt }
            - run: cargo fmt --all --check
